# Generated by Django 4.2.6 on 2024-02-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='clip',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
